const Region = [
    { key: "" ,   value: 'All country' },
    { key: "af", value: "Afghanistan" },
    { key: "al", value: "Albania" },
    { key: "dz", value: "Algeria" },
    { key: "as", value: "American Samoa" },
    { key: "ad", value: "Andorra" },
    { key: "ao", value: "Angola" },
    { key: "ai", value: "Anguilla" },
    { key: "ag", value: "Antigua &amp; Barbuda" },
    { key: "ar", value: "Argentina" },
    { key: "am", value: "Armenia" },
    { key: "au", value: "Australia" },
    { key: "at", value: "Austria" },
    { key: "az", value: "Azerbaijan" },
    { key: "bs", value: "Bahamas" },
    { key: "bh", value: "Bahrain" },
    { key: "bd", value: "Bangladesh" },
    { key: "by", value: "Belarus" },
    { key: "be", value: "Belgium" },
    { key: "bz", value: "Belize" },
    { key: "bj", value: "Benin" },
    { key: "bt", value: "Bhutan" },
    { key: "bo", value: "Bolivia" },
    { key: "ba", value: "Bosnia &amp; Herzegovina" },
    { key: "bw", value: "Botswana" },
    { key: "br", value: "Brazil" },
    { key: "vg", value: "British Virgin Islands" },
    { key: "bn", value: "Brunei" },
    { key: "bg", value: "Bulgaria" },
    { key: "bf", value: "Burkina Faso" },
    { key: "bi", value: "Burundi" },
    { key: "kh", value: "Cambodia" },
    { key: "cm", value: "Cameroon" },
    { key: "ca", value: "Canada" },
    { key: "cv", value: "Cape Verde" },
    { key: "cf", value: "Central African Republic" },
    { key: "td", value: "Chad" },
    { key: "cl", value: "Chile" },
    { key: "co", value: "Colombia" },
    { key: "cg", value: "Congo - Brazzaville" },
    { key: "cd", value: "Congo - Kinshasa" },
    { key: "ck", value: "Cook Islands" },
    { key: "cr", value: "Costa Rica" },
    { key: "ci", value: "Côte d’Ivoire" },
    { key: "hr", value: "Croatia" },
    { key: "cu", value: "Cuba" },
    { key: "cy", value: "Cyprus" },
    { key: "cz", value: "Czechia" },
    { key: "dk", value: "Denmark" },
    { key: "dj", value: "Djibouti" },
    { key: "dm", value: "Dominica" },
    { key: "do", value: "Dominican Republic" },
    { key: "ec", value: "Ecuador" },
    { key: "eg", value: "Egypt" },
    { key: "sv", value: "El Salvador" },
    { key: "ee", value: "Estonia" },
    { key: "et", value: "Ethiopia" },
    { key: "fj", value: "Fiji" },
    { key: "fi", value: "Finland" },
    { key: "fr", value: "France" },
    { key: "ga", value: "Gabon" },
    { key: "gm", value: "Gambia" },
    { key: "ge", value: "Georgia" },
    { key: "de", value: "Germany" },
    { key: "gh", value: "Ghana" },
    { key: "gi", value: "Gibraltar" },
    { key: "gr", value: "Greece" },
    { key: "gl", value: "Greenland" },
    { key: "gt", value: "Guatemala" },
    { key: "gg", value: "Guernsey" },
    { key: "gy", value: "Guyana" },
    { key: "ht", value: "Haiti" },
    { key: "hn", value: "Honduras" },
    { key: "hk", value: "Hong Kong" },
    { key: "hu", value: "Hungary" },
    { key: "is", value: "Iceland" },
    { key: "in", value: "India" },
    { key: "id", value: "Indonesia" },
    { key: "iq", value: "Iraq" },
    { key: "ie", value: "Ireland" },
    { key: "im", value: "Isle of Man" },
    { key: "il", value: "Israel" },
    { key: "it", value: "Italy" },
    { key: "jm", value: "Jamaica" },
    { key: "jp", value: "Japan" },
    { key: "je", value: "Jersey" },
    { key: "jo", value: "Jordan" },
    { key: "kz", value: "Kazakhstan" },
    { key: "ke", value: "Kenya" },
    { key: "ki", value: "Kiribati" },
    { key: "kw", value: "Kuwait" },
    { key: "kg", value: "Kyrgyzstan" },
    { key: "la", value: "Laos" },
    { key: "lv", value: "Latvia" },
    { key: "lb", value: "Lebanon" },
    { key: "ls", value: "Lesotho" },
    { key: "ly", value: "Libya" },
    { key: "li", value: "Liechtenstein" },
    { key: "lt", value: "Lithuania" },
    { key: "lu", value: "Luxembourg" },
    { key: "mg", value: "Madagascar" },
    { key: "mw", value: "Malawi" },
    { key: "my", value: "Malaysia" },
    { key: "mv", value: "Maldives" },
    { key: "ml", value: "Mali" },
    { key: "mt", value: "Malta" },
    { key: "mu", value: "Mauritius" },
    { key: "mx", value: "Mexico" },
    { key: "fm", value: "Micronesia" },
    { key: "md", value: "Moldova" },
    { key: "mn", value: "Mongolia" },
    { key: "me", value: "Montenegro" },
    { key: "ms", value: "Montserrat" },
    { key: "ma", value: "Morocco" },
    { key: "mz", value: "Mozambique" },
    { key: "mm", value: "Myanmar (Burma)" },
    { key: "na", value: "Namibia" },
    { key: "nr", value: "Nauru" },
    { key: "np", value: "Nepal" },
    { key: "nl", value: "Netherlands" },
    { key: "nz", value: "New Zealand" },
    { key: "ni", value: "Nicaragua" },
    { key: "ne", value: "Niger" },
    { key: "ng", value: "Nigeria" },
    { key: "nu", value: "Niue" },
    { key: "mk", value: "North Macedonia" },
    { key: "no", value: "Norway" },
    { key: "om", value: "Oman" },
    { key: "pk", value: "Pakistan" },
    { key: "ps", value: "Palestine" },
    { key: "pa", value: "Panama" },
    { key: "pg", value: "Papua New Guinea" },
    { key: "py", value: "Paraguay" },
    { key: "pe", value: "Peru" },
    { key: "ph", value: "Philippines" },
    { key: "pn", value: "Pitcairn Islands" },
    { key: "pl", value: "Poland" },
    { key: "pt", value: "Portugal" },
    { key: "pr", value: "Puerto Rico" },
    { key: "qa", value: "Qatar" },
    { key: "ro", value: "Romania" },
    { key: "ru", value: "Russia" },
    { key: "rw", value: "Rwanda" },
    { key: "ws", value: "Samoa" },
    { key: "sm", value: "San Marino" },
    { key: "st", value: "São Tomé &amp; Príncipe" },
    { key: "sa", value: "Saudi Arabia" },
    { key: "sn", value: "Senegal" },
    { key: "rs", value: "Serbia" },
    { key: "sc", value: "Seychelles" },
    { key: "sl", value: "Sierra Leone" },
    { key: "sg", value: "Singapore" },
    { key: "sk", value: "Slovakia" },
    { key: "si", value: "Slovenia" },
    { key: "sb", value: "Solomon Islands" },
    { key: "so", value: "Somalia" },
    { key: "za", value: "South Africa" },
    { key: "kr", value: "South Korea" },
    { key: "es", value: "Spain" },
    { key: "lk", value: "Sri Lanka" },
    { key: "sh", value: "St. Helena" },
    { key: "vc", value: "St. Vincent &amp; Grenadines" },
    { key: "sr", value: "Suriname" },
    { key: "se", value: "Sweden" },
    { key: "ch", value: "Switzerland" },
    { key: "tw", value: "Taiwan" },
    { key: "tj", value: "Tajikistan" },
    { key: "tz", value: "Tanzania" },
    { key: "th", value: "Thailand" },
    { key: "tl", value: "Timor-Leste" },
    { key: "tg", value: "Togo" },
    { key: "to", value: "Tonga" },
    { key: "tt", value: "Trinidad &amp; Tobago" },
    { key: "tn", value: "Tunisia" },
    { key: "tr", value: "Turkey" },
    { key: "tm", value: "Turkmenistan" },
    { key: "vi", value: "U.S. Virgin Islands" },
    { key: "ug", value: "Uganda" },
    { key: "ua", value: "Ukraine" },
    { key: "ae", value: "United Arab Emirates" },
    { key: "gb", value: "United Kingdom" },
    { key: "us", value: "United States" },
    { key: "uy", value: "Uruguay" },
    { key: "uz", value: "Uzbekistan" },
    { key: "vu", value: "Vanuatu" },
    { key: "ve", value: "Venezuela" },
    { key: "vn", value: "Vietnam" },
    { key: "zm", value: "Zambia" },
    { key: "zw", value: "Zimbabwe" },
    // { value: 'All country', key: "" },
    // { value: 'Afghanistan', key: "countryAF" },
    // { value: 'Albania', key: "countryAL" },
    // { value: 'Algeria', key: "countryDZ" },
    // { value: 'American Samoa', key: "countryAS" },
    // { value: 'Andorra', key: "countryAD" },
    // { value: 'Angola', key: "countryAO" },
    // { value: 'Anguilla', key: "countryAI" },
    // { value: 'Antarctica', key: "countryAQ" },
    // { value: 'Antigua and Barbuda', key: "countryAG" },
    // { value: 'Argentina', key: "countryAR" },
    // { value: 'Armenia', key: "countryAM" },
    // { value: 'Aruba', key: "countryAW" },
    // { value: 'Australia', key: "countryAU" },
    // { value: 'Austria', key: "countryAT" },
    // { value: 'Azerbaijan', key: "countryAZ" },
    // { value: 'Bahamas', key: "countryBS" },
    // { value: 'Bahrain', key: "countryBH" },
    // { value: 'Bangladesh', key: "countryBD" },
    // { value: 'Barbados', key: "countryBB" },
    // { value: 'Belarus', key: "countryBY" },
    // { value: 'Belgium', key: "countryBE" },
    // { value: 'Belize', key: "countryBZ" },
    // { value: 'Benin', key: "countryBJ" },
    // { value: 'Bermuda', key: "countryBM" },
    // { value: 'Bhutan', key: "countryBT" },
    // { value: 'Bolivia', key: "countryBO" },
    // { value: 'Bosnia and Herzegovina', key: "countryBA" },
    // { value: 'Botswana', key: "countryBW" },
    // { value: 'Bouvet Island', key: "countryBV" },
    // { value: 'Brazil', key: "countryBR" },
    // { value: 'British Indian Ocean Territory', key: "countryIO" },
    // { value: 'Brunei Darussalam', key: "countryBN" },
    // { value: 'Bulgaria', key: "countryBG" },
    // { value: 'Burkina Faso', key: "countryBF" },
    // { value: 'Burundi', key: "countryBI" },
    // { value: 'Cambodia', key: "countryKH" },
    // { value: 'Cameroon', key: "countryCM" },
    // { value: 'Canada', key: "countryCA" },
    // { value: 'Cape Verde', key: "countryCV" },
    // { value: 'Cayman Islands ', key: "countryKY" },
    // { value: 'Central African Republic', key: "countryCF" },
    // { value: 'Chad', key: "countryTD" },
    // { value: 'Chile', key: "countryCL" },
    // { value: 'China', key: "countryCN" },
    // { value: 'Christmas Island', key: "countryCX" },
    // { value: 'Cocos (Keeling) Islands', key: "countryCC" },
    // { value: 'Colombia', key: "countryCO" },
    // { value: 'Comoros', key: "countryKM" },
    // { value: 'Congo', key: "countryCG" },
    // { value: 'Congo  the Democratic Republic of the the Democratic Republic of the ', key: "countryCD" },
    // { value: 'Cook Islands', key: "countryCK" },
    // { value: 'Costa Rica', key: "countryCR" },
    // { value: 'Cote Divoire', key: "countryCI" },
    // { value: 'Croatia (Hrvatska)', key: "countryHR" },
    // { value: 'Cuba', key: "countryCU" },
    // { value: ' Cyprus', key: "countryCY" },
    // { value: 'Czech Republic', key: "countryCZ" },
    // { value: 'Denmark', key: "countryDK" },
    // { value: 'Djibouti', key: "countryDJ" },
    // { value: 'Dominica', key: "countryDM" },
    // { value: 'Dominican Republic', key: "countryDO" },
    // { value: 'East Timor', key: "countryTP" },
    // { value: 'Ecuador', key: "countryEC" },
    // { value: 'Egypt', key: "countryEG" },
    // { value: 'El Salvador', key: "countrySV" },
    // { value: 'Equatorial Guinea', key: "countryGQ" },
    // { value: 'Eritrea', key: "countryER" },
    // { value: 'Estonia', key: "countryEE" },
    // { value: 'Ethiopia', key: "countryET" },
    // { value: 'European Union', key: "countryEU" },
    // { value: 'Falkland Islands (Malvinas)', key: "countryFK" },
    // { value: 'Faroe Islands', key: "countryFO" },
    // { value: 'Fiji', key: "countryFJ" },
    // { value: 'Finland', key: "countryFI" },
    // { value: 'France', key: "countryFR" },
    // { value: 'France Metropolitan', key: "countryFX" },
    // { value: 'French Guiana', key: "countryGF" },
    // { value: 'French Polynesia', key: "countryPF" },
    // { value: 'French Southern Territories', key: "countryTF" },
    // { value: 'Gabon', key: "countryGA" },
    // { value: 'Gambia', key: "countryGM" },
    // { value: 'Georgia', key: "countryGE" },
    // { value: 'Germany', key: "countryDE" },
    // { value: 'Ghana', key: "countryGH" },
    // { value: 'Gibraltar', key: "countryGI" },
    // { value: 'Greece', key: "countryGR" },
    // { value: 'Greenland', key: "countryGL" },
    // { value: 'Grenada', key: "countryGD" },
    // { value: 'Guadeloupe', key: "countryGP" },
    // { value: 'Guam', key: "countryGU" },
    // { value: 'Guatemala', key: "countryGT" },
    // { value: 'Guinea', key: "countryGN" },
    // { value: 'Guinea-Bissau', key: "countryGW" },
    // { value: 'Guyana', key: "countryGY" },
    // { value: 'Haiti', key: "countryHT" },
    // { value: 'Heard Island and Mcdonald Islands', key: "countryHM" },
    // { value: 'Holy See (Vatican City State)', key: "countryVA" },
    // { value: 'Honduras', key: "countryHN" },
    // { value: 'Hong Kong', key: "countryHK" },
    // { value: 'Hungary', key: "countryHU" },
    // { value: 'Iceland', key: "countryIS" },
    // { value: 'India', key: "countryIN" },
    // { value: 'Indonesia', key: "countryID" },
    // { value: 'Iran, Islamic Republic of', key: "countryIR" },
    // { value: 'Iraq', key: "countryIQ" },
    // { value: 'Ireland', key: "countryIE" },
    // { value: 'Israel', key: "countryIL" },
    // { value: 'Italy', key: "countryIT" },
    // { value: 'Jamaica', key: "countryJM" },
    // { value: 'Japan', key: "countryJP" },
    // { value: 'Jordan', key: "countryJO" },
    // { value: 'Kazakhstan', key: "countryKZ" },
    // { value: 'Kenya', key: "countryKE" },
    // { value: 'Kiribati', key: "countryKI" },
    // { value: 'Korea, Democratic Peoples Republic of	', key: "countryKP" },
    // { value: 'Korea, Republic of', key: "countryKR" },
    // { value: 'Kuwait', key: "countryKW" },
    // { value: 'Kyrgyzstan', key: "countryKG" },
    // { value: 'Lao Peoples Democratic Republic', key: "countryLA" },
    // { value: 'Latvia', key: "countryLV" },
    // { value: 'Lesotho', key: "countryLS" },
    // { value: 'Liberia', key: "countryLR" },
    // { value: 'Libyan Arab Jamahiriya', key: "countryLY" },
    // { value: 'Liechtenstein', key: "countryLI" },
    // { value: 'Lithuania', key: "countryLT" },
    // { value: 'Luxembourg', key: "countryLU" },
    // { value: 'Macao', key: "countryMO" },
    // { value: 'Macedonia, the Former Yugosalv Republic of', key: "countryMK" },
    // { value: 'Madagascar', key: "countryMG" },
    // { value: 'Malawi', key: "countryMW" },
    // { value: 'Malaysia', key: "countryMY" },
    // { value: 'Maldives', key: "countryMV" },
    // { value: 'Mali', key: "countryML" },
    // { value: 'Malta', key: "countryMT" },
    // { value: 'Marshall Islands', key: "countryMH" },
    // { value: 'Martinique', key: "countryMQ" },
    // { value: 'Mauritania', key: "countryMR" },
    // { value: 'Mauritius', key: "countryMU" },
    // { value: 'Mayotte', key: "countryYT" },
    // { value: 'Mexico', key: "countryMX" },
    // { value: 'Micronesia, Federated States of', key: "countryFM" },
    // { value: 'Moldova, Republic of', key: "countryMD" },
    // { value: 'Monaco', key: "countryMC" },
    // { value: 'Mongolia', key: "countryMN" },
    // { value: 'Montserrat', key: "countryMS" },
    // { value: 'Morocco', key: "countryMA" },
    // { value: 'Mozambique', key: "countryMZ" },
    // { value: 'Myanmar', key: "countryMM" },
    // { value: 'Namibia', key: "countryNA" },
    // { value: 'Nauru', key: "countryNR" },
    // { value: 'Nepal', key: "countryNP" },
    // { value: 'Netherlands', key: "countryNL" },
    // { value: 'Netherlands Antilles', key: "countryAN" },
    // { value: ' New Caledonia', key: "countryNC" },
    // { value: ' New Zealand', key: "countryNZ" },
    // { value: 'Nicaragua', key: "countryNI" },
    // { value: 'Niger', key: "countryNE" },
    // { value: 'Nigeria', key: "countryNG" },
    // { value: 'Niue', key: "countryNU" },
    // { value: 'Norfolk Island', key: "countryNF" },
    // { value: 'Northern Mariana Islands', key: "countryMP" },
    // { value: 'Norway', key: "countryNO" },
    // { value: 'Oman', key: "countryOM" },
    // { value: 'Pakistan', key: "countryPK" },
    // { value: 'Palau', key: "countryPW" },
    // { value: 'Palestinian Territory', key: "countryPS" },
    // { value: 'Panama	', key: "countryPA" },
    // { value: 'Papua New Guinea', key: "countryPG" },
    // { value: 'Paraguay', key: "countryPY" },
    // { value: 'Peru', key: "countryPE" },
    // { value: 'Philippines', key: "countryPH" },
    // { value: 'Pitcairn', key: "countryPN" },
    // { value: 'Poland', key: "countryPL" },
    // { value: 'Portugal', key: "countryPT" },
    // { value: 'Puerto Rico', key: "countryPR" },
    // { value: 'Qatar', key: "countryQA" },
    // { value: 'Reunion', key: "countryRE" },
    // { value: 'Romania', key: "countryRO" },
    // { value: 'Russian Federation', key: "countryRU" },
    // { value: 'Rwanda', key: "countryRW" },
    // { value: 'Saint Helena', key: "countrySH" },
    // { value: 'Saint Kitts and Nevis', key: "countryKN" },
    // { value: 'Saint Lucia', key: "countryLC" },
    // { value: 'Saint Pierre and MiqueloncountryPM', key: "" },
    // { value: 'Saint Vincent and the Grenadines', key: "countryVC" },
    // { value: 'Samoa', key: "countryWS" },
    // { value: 'San Marino', key: "countrySM" },
    // { value: '  Sao Tome and Principe', key: "countryST" },
    // { value: 'Saudi Arabia', key: "countrySA" },
    // { value: 'Senegal', key: "countrySN" },
    // { value: 'Serbia and Montenegro', key: "countryCS" },
    // { value: 'Seychelles', key: "countrySC" },
    // { value: 'Sierra Leone', key: "countrySL" },
    // { value: 'Singapore', key: "countrySG" },
    // { value: 'Slovakia', key: "countrySK" },
    // { value: 'Slovenia', key: "countrySI" },
    // { value: 'Solomon Islands', key: "countrySB" },
    // { value: 'Somalia', key: "countrySO" },
    // { value: 'South Africa', key: "countryZA" },
    // { value: 'South Georgia and the South Sandwich', key: "IslandscountryGS" },
    // { value: 'Spain', key: "countryES" },
    // { value: 'Sri Lanka', key: "countryLK" },
    // { value: 'Sudan', key: "countrySD" },
    // { value: 'Suriname', key: "countrySR" },
    // { value: 'Svalbard and Jan Mayen', key: "countrySJ" },
    // { value: 'Swaziland', key: "countrySZ" },
    // { value: 'Sweden', key: "countrySE" },
    // { value: 'Switzerland', key: "countryCH" },
    // { value: 'Syrian Arab Republic', key: "countrySY" },
    // { value: 'Taiwan, Province of China', key: "countryTW" },
    // { value: 'Tajikistan', key: "countryTJ" },
    // { value: 'Tanzania, United Republic of', key: "countryTZ" },
    // { value: 'Thailand', key: "countryTH" },
    // { value: 'Togo', key: "countryTG" },
    // { value: 'Tokelau', key: "countryTK" },
    // { value: 'Tonga', key: "countryTO" },
    // { value: 'Trinidad and Tobago', key: "countryTT" },
    // { value: 'Tunisia', key: "countryTN" },
    // { value: 'Turkey', key: "countryTR" },
    // { value: 'Turkmenistan', key: "countryTM" },
    // { value: 'Turks and Caicos Islands', key: "countryTC" },
    // { value: 'Tuvalu', key: "countryTV" },
    // { value: 'Uganda', key: "countryUG" },
    // { value: 'Ukraine', key: "countryUA" },
    // { value: 'United Arab Emirates', key: "countryAE" },
    // { value: 'United States', key: "countryUS" },
    // { value: 'United States Minor Outlying Islands', key: "countryUM" },
    // { value: 'Uruguay', key: "countryUY" },
    // { value: 'Uzbekistan', key: "countryUZ" },
    // { value: 'Vanuatu', key: "countryVU" },
    // { value: 'Venezuela', key: "countryVE" },
    // { value: 'Vietnam', key: "countryVN" },
    // { value: 'Virgin Islands, British', key: "countryVG" },
    // { value: 'Virgin Islands, U.S.', key: "countryVI" },
    // { value: 'Wallis and Futuna', key: "countryWF" },
    // { value: 'Western Sahara', key: "countryEH" },
    // { value: 'Yemen', key: "countryYE" },
    // { value: 'Yugoslavia', key: "countryYU" },
    // { value: 'Zambia', key: "countryZM" },
    // { value: 'Zimbabwe', key: "countryZW" },
]
export default Region;
















