const Region = [
    { key: "",   value: "All country" },
    { key: "af", value: "Afghanistan" },
    { key: "al", value: "Albania" },
    { key: "dz", value: "Algeria" },
    { key: "as", value: "American Samoa" },
    { key: "ad", value: "Andorra" },
    { key: "ao", value: "Angola" },
    { key: "ai", value: "Anguilla" },
    { key: "aq", value: "Antarctica" },
    { key: "ag", value: "Antigua and Barbuda" },
    { key: "ar", value: "Argentina" },
    { key: "am", value: "Armenia" },
    { key: "aw", value: "Aruba"},
    { key: "au", value: "Australia" },
    { key: "at", value: "Austria" },
    { key: "az", value: "Azerbaijan" },
    { key: "bs", value: "Bahamas" },
    { key: "bh", value: "Bahrain" },
    { key: "bd", value: "Bangladesh" },
    { key: "bb", value: "Barbados" },
    { key: "by", value: "Belarus" },
    { key: "be", value: "Belgium" },
    { key: "bz", value: "Belize" },
    { key: "bj", value: "Benin" },
    { key: "bm", value: "Bermuda" },
    { key: "bt", value: "Bhutan" },
    { key: "bo", value: "Bolivia" },
    { key: "ba", value: "Bosnia and Herzegovina" },
    { key: "bw", value: "Botswana" },
    { key: "bv", value: "Bouvet Island" },
    { key: "br", value: "Brazil" },
    { key: "vg", value: "British Virgin Islands" },//
    { key: "io", value: "British Indian Ocean Territory" },
    { key: "bn", value: "Brunei Darussalam" },
    { key: "bg", value: "Bulgaria" },
    { key: "bf", value: "Burkina Faso" },
    { key: "bi", value: "Burundi" },
    { key: "cv", value: "Cabo Verde" },//
    { key: "kh", value: "Cambodia" },
    { key: "cm", value: "Cameroon" },
    { key: "ca", value: "Canada" },
    { key: "cv", value: "Cape Verde" },
    { key: "ky", value: "Cayman Islands " },
    { key: "cc", value: "Cocos (Keeling) Islands" },
    { key: "cf", value: "Central African Republic" },
    { key: "td", value: "Chad" },
    { key: "cl", value: "Chile" },
    { key: "cn", value: "China" },
    { key: "cx", value: "Christmas Island" },
    { key: "co", value: "Colombia" },
    { key: "km", value: "Comoros" }, 
    { key: "cg", value: "Congo - Brazzaville" },
    { key: "cd", value: "Congo - Kinshasa" },
    { key: "ck", value: "Cook Islands" },
    { key: "cr", value: "Costa Rica" },
    { key: "ci", value: "Cote Divoire" },
    { key: "hr", value: "Croatia (Hrvatska)" },
    { key: "cu", value: "Cuba" },
    { key: "cy", value: "Cyprus" },
    { key: "cz", value: "Czechia" },
    { key: "dk", value: "Denmark" },
    { key: "dj", value: "Djibouti" },
    { key: "dm", value: "Dominica" },
    { key: "do", value: "Dominican Republic" },
    { key: "tp", value: "East Timor"},//
    { key: "ec", value: "Ecuador" },
    { key: "eg", value: "Egypt" },
    { key: "sv", value: "El Salvador" },
    { key: "gq", value: "Equatorial Guinea" },
    { key: "er", value: "Eritrea" },
    { key: "ee", value: "Estonia" },
    { key: "sz", value: "Eswatini" },//
    { key: "et", value: "Ethiopia" },
    { key: "fk", value: "Falkland Islands (Malvinas)" },
    { key: "fo", value: "Faroe Islands" },
    { key: "fj", value: "Fiji" },
    { key: "fi", value: "Finland" },
    { key: "fr", value: "France" },
    { key: "gf", value: "French Guiana" },
    { key: "pf", value: "French Polynesia" },
    { key: "ga", value: "Gabon" },
    { key: "gm", value: "Gambia" },
    { key: "ge", value: "Georgia" },
    { key: "de", value: "Germany" },
    { key: "gh", value: "Ghana" },
    { key: "gi", value: "Gibraltar" },
    { key: "gr", value: "Greece" },
    { key: "gl", value: "Greenland" },
    { key: "gd", value: "Grenada" },
    { key: "gp", value: "Guadeloupe"},
    { key: "gu", value: "Guam" },
    { key: "gt", value: "Guatemala" },
    { key: "gn", value: "Guinea"},
    { key: "gw", value: "Guinea-Bissau"},
    { key: "gg", value: "Guernsey" },//
    { key: "gy", value: "Guyana" },
    { key: "ht", value: "Haiti" },
    { key: "hn", value: "Honduras" },
    { key: "hk", value: "Hong Kong" },
    { key: "hu", value: "Hungary" },
    { key: "is", value: "Iceland" },
    { key: "in", value: "India" },
    { key: "id", value: "Indonesia" },
    { key: "ir", value: "Iran" },
    { key: "iq", value: "Iraq" },
    { key: "ie", value: "Ireland" },
    { key: "il", value: "Israel" },
    { key: "it", value: "Italy" },
    { key: "jm", value: "Jamaica" },
    { key: "jp", value: "Japan" },
    { key: "je", value: "Jersey" },//
    { key: "jo", value: "Jordan" },
    { key: "kz", value: "Kazakhstan" },
    { key: "ke", value: "Kenya" },
    { key: "ki", value: "Kiribati" },
    { key: "kr", value: "Korea" },
    { key: "kw", value: "Kuwait" },
    { key: "kg", value: "Kyrgyzstan" },
    { key: "la", value: "Laos" },
    { key: "lv", value: "Latvia" },
    { key: "lb", value: "Lebanon" },
    { key: "ls", value: "Lesotho" },
    { key: "lr", value: "Liberia" },
    { key: "ly", value: "Libya" },
    { key: "li", value: "Liechtenstein" },
    { key: "lt", value: "Lithuania" },
    { key: "lu", value: "Luxembourg" },
    { key: "mo", value: "Macao" },
    { key: "mg", value: "Madagascar" },
    { key: "mw", value: "Malawi" },
    { key: "my", value: "Malaysia" },
    { key: "mv", value: "Maldives" },
    { key: "ml", value: "Mali" },
    { key: "mt", value: "Malta" },
    { key: "mh", value: "Marshall Islands" },
    { key: "mq", value: "Martinique" },
    { key: "mr", value: "Mauritania"},
    { key: "mu", value: "Mauritius" },
    { key: "yt", value: "Mayotte"},
    { key: "mx", value: "Mexico" },
    { key: "fm", value: "Micronesia" },
    { key: "md", value: "Moldova" },
    { key: "mc", value: "Monaco" },
    { key: "mn", value: "Mongolia" },
    { key: "me", value: "Montenegro" },//
    { key: "ms", value: "Montserrat" },
    { key: "ma", value: "Morocco" },
    { key: "mz", value: "Mozambique" },
    { key: "mm", value: "Myanmar" },
    { key: "na", value: "Namibia" },
    { key: "nr", value: "Nauru" },
    { key: "np", value: "Nepal" },
    { key: "nl", value: "Netherlands" },
    { key: "nc", value: "New Caledonia" },
    { key: "nz", value: "New Zealand" },
    { key: "ni", value: "Nicaragua" },
    { key: "ne", value: "Niger" },
    { key: "ng", value: "Nigeria" },
    { key: "nu", value: "Niue" },
    { key: "nf", value: "Norfolk Island" },
    { key: "mk", value: "North Macedonia" },//
    { key: "no", value: "Norway" },
    { key: "om", value: "Oman" },
    { key: "pk", value: "Pakistan" },
    { key: "pw", value: "Palau" },
    { key: "ps", value: "Palestine" },
    { key: "pa", value: "Panama" },
    { key: "pg", value: "Papua New Guinea" },
    { key: "py", value: "Paraguay" },
    { key: "pe", value: "Peru" },
    { key: "ph", value: "Philippines" },
    { key: "pn", value: "Pitcairn Islands" },
    { key: "pl", value: "Poland" },
    { key: "pt", value: "Portugal" },
    { key: "pr", value: "Puerto Rico" },
    { key: "qa", value: "Qatar" },
    { key: "re", value: "Reunion" },
    { key: "ro", value: "Romania" },
    { key: "ru", value: "Russia" },
    { key: "rw", value: "Rwanda" },
    { key: "kn", value: "Saint Kitts and Nevis" },
    { key: "lc", value: "Saint Lucia" },
    { key: "pm", value: "Saint Pierre and Miquelon" },
    { key: "vc", value: "Saint Vincent and the Grenadines" },
    { key: "ws", value: "Samoa" },
    { key: "sm", value: "San Marino" },
    { key: "st", value: "Sao Tome and Principe" },
    { key: "sa", value: "Saudi Arabia" },
    { key: "sn", value: "Senegal" },
    { key: "rs", value: "Serbia" },//
    { key: "sc", value: "Seychelles" },
    { key: "sl", value: "Sierra Leone" },
    { key: "sg", value: "Singapore" },
    { key: "sk", value: "Slovakia" },
    { key: "si", value: "Slovenia" },
    { key: "sb", value: "Solomon Islands" },
    { key: "so", value: "Somalia" },
    { key: "za", value: "South Africa" },
    { key: "ss", value: "South Sudan" },//
    { key: "kr", value: "South Korea" },//
    { key: "es", value: "Spain" },
    { key: "lk", value: "Sri Lanka" },
    { key: "sd", value: "Sudan" },
    { key: "sr", value: "Suriname" },
    { key: "sh", value: "St. Helena" },//
    { key: "vc", value: "St. Vincent and Grenadines" },//
    { key: "se", value: "Sweden" },
    { key: "ch", value: "Switzerland" },
    { key: "sy", value: "Syria" },
    { key: "tw", value: "Taiwan" },
    { key: "tj", value: "Tajikistan" },
    { key: "tz", value: "Tanzania" },
    { key: "th", value: "Thailand" },
    { key: "tg", value: "Togo" },
    { key: "tk", value: "Tokelau"},
    { key: "to", value: "Tonga" },
    { key: "tt", value: "Trinidad and Tobago" },
    { key: "tn", value: "Tunisia" },
    { key: "tr", value: "Turkey" },
    { key: "tm", value: "Turkmenistan" },
    { key: "tc", value: "Turks and Caicos Islands" },
    { key: "tv", value: "Tuvalu" },
    { key: "vi", value: "U.S. Virgin Islands" },
    { key: "ug", value: "Uganda" },
    { key: "ua", value: "Ukraine" },
    { key: "ae", value: "United Arab Emirates" },
    { key: "gb", value: "United Kingdom" },
    { key: "us", value: "United States" },
    { key: "uy", value: "Uruguay" },
    { key: "uz", value: "Uzbekistan" },
    { key: "vu", value: "Vanuatu" },
    { key: "ve", value: "Venezuela" },
    { key: "vn", value: "Vietnam" },
    { key: "wf", value: "Wallis and Futuna"},
    { key: "ye", value: "Yemen" },
    { key: "zm", value: "Zambia" },
    { key: "zw", value: "Zimbabwe" },
]
export default Region;
















